(228) Cancer type/condition tests
NCIOCPL/clinical-trials-search-app pull request #254
Opened 2021-08-09 18:34 UTC by kate-mashkina

- mocked request and response
- added feature file
Closes #228

2021-08-20 14:15 UTC, bryanpizzillo requested changes
Please update the commit comment for "-fixed a bug in mocking disease request" to explain what the bug was. (This is in lieu of requesting a separate git ticket and a separate commit.)

I see nothing that actually explains what this was other than "kate changed this". Which will be treated as "why did she do this, what was the actual bug???"

Additionally, the comment
```
  // File naming is
  // <codes>_<types>_<size>_<sort>
  // codes can be 
  // C1-C2-C3 to separate the disease concepts
  // each disease concept can have multiple IDs comma separated
  // so we could have C1,C2-C3-C4,C5 if we have 3 concepts, C1,C2 and C3 and C4,C5
```

Needs to be updated to add in the additional parameters.

2021-08-20 19:03 UTC, bryanpizzillo commented
This PR should cover components/search-modules/CancerTypeCondition

![image](https://user-images.githubusercontent.com/11215649/130281701-4679ebf6-4097-47fe-941d-b123772e3b8e.png)

2021-08-25 01:46 UTC, kate-mashkina commented
@bryanpizzillo coverage is up to almost a 100 % ( functions are at exactly 100 %)

2021-08-30 14:29 UTC, bryanpizzillo approved these changes

2021-08-30 14:29 UTC, merged