(#231) Advanced Search Page -- Trial Type Section tests
NCIOCPL/clinical-trials-search-app pull request #264
Opened 2021-08-11 22:56 UTC by adriancofie

Adds feature file for Advanced Search Page
Adds additional step implementations to common/index.js

Closes #231

2021-09-01 15:58 UTC, kate-mashkina approved these changes

2021-09-02 15:16 UTC, bryanpizzillo requested changes
Can you please add a test for Healthy Volunteer and All

2021-09-02 17:01 UTC, kate-mashkina commented
@bryanpizzillo scenario is added

2021-09-02 18:31 UTC, bryanpizzillo approved these changes

2021-09-02 18:31 UTC, merged