(#395)Implement Search Criteria on Trial Results
NCIOCPL/clinical-trials-search-app pull request #429
Opened 2021-11-29 21:37 UTC by kate-mashkina

Closes #395 
Closes #434

2021-12-08 14:32 UTC, arcepaul commented on src/views/ResultsPage/ResultsPageHeader.jsx
> +				<>
no fragment needed here

2021-12-08 14:35 UTC, arcepaul approved these changes

2021-12-08 15:24 UTC, KateMashkinaNIH commented on src/views/ResultsPage/ResultsPageHeader.jsx
> +				<>
removed it

2021-12-08 17:43 UTC, bryanpizzillo requested changes
This needs Redux removed.

2021-12-08 20:10 UTC, sarinapadilla commented
@kate-mashkina demo'd the Search Criteria Table functionality for both me and @VictoriaSunNIH and it's looking good, so this passes from a UX perspective!

2021-12-09 14:46 UTC, bryanpizzillo approved these changes

2021-12-09 14:46 UTC, merged