(#573) Update help (?) link anchor links to point to correct sections of the help page on basic form
NCIOCPL/clinical-trials-search-app pull request #575
Opened 2022-08-01 15:46 UTC by alerosad

- updated help links, along with integration tests accordingly

Closes #573

2022-08-01 15:49 UTC, alerosad commented
Since the page still isn't created on the ODE, the redirect on react-app-dev will bring you to a page that says not found in the time being

2022-08-01 15:49 UTC, alerosad commented
https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-575

2022-08-01 16:27 UTC, seyilonge-nci approved these changes

2022-08-01 16:56 UTC, sarinapadilla commented
Since the help link URL is a relative path that does not include the basePath (for v2 launch), the page will resolve to a 404 on react-app-dev. Once on the ODE, these links will take you to the correct path. This looks good to me!

2022-08-01 17:00 UTC, alinai commented
@sarinapadilla , this is how I am seeing the Page Not Found on the https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-575 compared to any 404 pages on test-ac (CTS on dev-ac is down now, so I verified on test-ac). Is it expected?

![image](https://user-images.githubusercontent.com/28455973/182203047-c039cab0-749c-4e4c-9f37-cac708abc5f9.png)
![image](https://user-images.githubusercontent.com/28455973/182203390-f8aafaa9-f758-4df7-96f1-ad267b24e355.png)

2022-08-01 17:01 UTC, sarinapadilla commented
@alinai test-ac does not have the help page content. On the ODE, it will be there!

2022-08-01 17:05 UTC, sarinapadilla commented
@alinai yes it does. Go to any test-ac 404 and you'll see it looks different than react-app-dev
<img width="576" alt="Screen Shot 2022-08-01 at 1 04 23 PM" src="https://user-images.githubusercontent.com/24591940/182204026-daa55f40-b750-461c-96ce-5e3ce0e73a2d.png">
!

2022-08-01 17:17 UTC, sarinapadilla commented
@alinai it's expected; basic form help links all link to one section on the help page, while advanced form fields all link to their own section.

2022-08-01 17:21 UTC, sarinapadilla commented
@alerosad actually this doesn't pass. The advanced Cancer Type/Condition, Age, and Keyword fields are linking to the basic section. These need to stay as they currently are (help#cancertype, help#age, help#keywords respectively)

2022-08-01 22:56 UTC, seyilonge-nci requested changes

2022-08-01 22:56 UTC, seyilonge-nci commented on cypress/integration/BasicSearchPage/BasicSearchPage.feature
> +		And help icon is displayed in "Age" section with href "/about-cancer/treatment/clinical-trials/search/help#how-to-find-clinical-trials-using-the-basic-search-form"
Shouldn't this remain the same since it wasn't changed in the component?

2022-08-01 23:52 UTC, sarinapadilla commented
This looks good to me!

2022-08-02 13:22 UTC, alinai commented
@sarinapadilla , the 'Age' section in both Basic and Advanced form is now linking to help#age. Please confirm if this is expected.

2022-08-02 13:39 UTC, sarinapadilla commented
@alinai it's expected - only Cancer Type/Keywords and ZIP on the basic form should be changing. The rest of the help links are staying the same.

2022-08-02 13:43 UTC, alinai commented
> @alinai it's expected - only Cancer Type/Keywords and ZIP on the basic form should be changing. The rest of the help links are staying the same.

Thanks @sarinapadilla for confirming. Looks good to me as well.

2022-08-02 14:33 UTC, seyilonge-nci commented on cypress/integration/BasicSearchPage/BasicSearchPage.feature
> +		And help icon is displayed in "Age" section with href "/about-cancer/treatment/clinical-trials/search/help#how-to-find-clinical-trials-using-the-basic-search-form"
> Shouldn't this remain the same since it wasn't changed in the component?

Okay with the change after recent push

2022-08-02 14:33 UTC, seyilonge-nci approved these changes

2022-08-02 15:06 UTC, merged